version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          name: "Build"
          command: |
            sudo apt update
            sudo apt install python3 python3-pip docker-cli
            # curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            # sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
            # sudo apt install -y libpcap-dev libsctp-dev libncurses5-dev libssl-dev libgsl0-dev sip-tester docker-ce
            sudo pip3 install . -r requirements-test.txt
      - run:
          name: "Test"
          command: |
            docker ps
            pytest --use-docker tests/ -vv


workflows:
  main:
    jobs:
      - build
