version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          name: "Build"
          command: |
            sudo apt update
            sudo apt install python3 python3-pip docker
            # curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            # sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
            # sudo apt install -y libpcap-dev libsctp-dev libncurses5-dev libssl-dev libgsl0-dev sip-tester docker-ce
            sudo pip3 install . -r requirements-test.txt
      - run:
          name: "Test"
          command: |
            docker run -d --name freeswitch -e SOUND_RATES=8000:16000 -e SOUND_TYPES=music:en-us-callie -v freeswitch-sounds:/usr/share/freeswitch/sounds -v  $(pwd)/conf/ci-minimal/:/etc/freeswitch   safarov/freeswitch:1.10.3
            docker inspect freeswitch
            pytest --use-docker tests/ -vv


workflows:
  main:
    jobs:
      - build
