# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ experiement ]
  pull_request:
    branches: [ experiment ]

jobs:
  test:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python_version: ['3.7']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install system dependencies
      run: |
        sudo apt update
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        sudo apt install -y libpcap-dev libsctp-dev libncurses5-dev libssl-dev libgsl0-dev sip-tester docker-ce
    - name: Install app dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install . -r requirements-test.txt
    - name: Test with pytest
      run: |
        ls -la conf
        docker run -d --net=bridge --name freeswitch -e SOUND_RATES=8000:16000 -e SOUND_TYPES=music:en-us-callie -v freeswitch-sounds:/usr/share/freeswitch/sounds -v $(pwd)/conf/ci-minimal/:/etc/freeswitch safarov/freeswitch:1.10.3
        sleep 20
        docker logs freeswitch
        pytest --use-docker tests/
