# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ['3.6', '3.7', '3.8']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Docker
      uses: docker-practice/actions-setup-docker@v1
      with:
        docker_channel: stable
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install system dependencies
      run: |
        sudo apt install -y libpcap-dev libsctp-dev libncurses5-dev libssl-dev libgsl0-dev
        git clone https://github.com/SIPp/sipp.git && cd sipp && ./build.sh --full
        export PATH=\"$PWD:$PATH\"
        cd ..
    - name: Install app dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install . -r requirements-test.txt
    - name: Test with pytest
      run: |
        pytest --use-docker tests/
